name = "cloudflare-guestbook2"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "MESSAGES"
id = "3fc418eb9e924e2bb288836aa1021e16"

[vars]
# GitHub 配置用于文件上传
GITHUB_TOKEN = "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"
GITHUB_REPO = "HERO-WPC/herochat"
GITHUB_BRANCH = "main"  # 可选，默认为 main
GITHUB_PATH = "uploads/"  # 可选，默认为 uploads/
